// backend/seeders/adminSeeder.js
const { executeQuery, initializeDatabase, closeDatabase } = require('../config/database');
const bcrypt = require('bcryptjs');

class AdminSeeder {
    static async createAdminTables() {
        try {
            console.log('Creating admin tables...');

            try {
                await executeQuery(`
                    CREATE TABLE SYSTEM_CONFIG (
                        CONFIG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        CONFIG_KEY VARCHAR2(100) NOT NULL UNIQUE,
                        CONFIG_VALUE CLOB,
                        CONFIG_TYPE VARCHAR2(50) DEFAULT 'STRING',
                        DESCRIPTION VARCHAR2(500),
                        IS_ACTIVE NUMBER(1) DEFAULT 1,
                        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                `);
                console.log('SYSTEM_CONFIG table created');
            } catch (error) {
                if (error.message && error.message.includes('name is already used')) {
                    console.log('SYSTEM_CONFIG table already exists');
                } else {
                    throw error;
                }
            }

            try {
                await executeQuery(`
                    CREATE TABLE ADMIN_LOGS (
                        LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ADMIN_ID NUMBER NOT NULL,
                        ACTION_TYPE VARCHAR2(100) NOT NULL,
                        DESCRIPTION CLOB,
                        IP_ADDRESS VARCHAR2(45),
                        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT FK_ADMIN_LOGS_USER FOREIGN KEY (ADMIN_ID) REFERENCES USERS(ID)
                    )
                `);
                console.log('ADMIN_LOGS table created');
            } catch (error) {
                if (error.message && error.message.includes('name is already used')) {
                    console.log('ADMIN_LOGS table already exists');
                } else {
                    throw error;
                }
            }

            const defaultConfigs = [
                ['MAINTENANCE_MODE', 'false', 'BOOLEAN', 'System maintenance mode'],
                ['ENABLE_REGISTRATION', 'true', 'BOOLEAN', 'Allow new user registration'],
                ['ENABLE_CHAT', 'true', 'BOOLEAN', 'Enable chat functionality'],
                ['ENABLE_AI', 'true', 'BOOLEAN', 'Enable AI assistant'],
                ['MAX_USERS', '10000', 'NUMBER', 'Maximum number of users'],
                ['MAX_FILE_SIZE', '10485760', 'NUMBER', 'Maximum file size in bytes'],
                ['RATE_LIMIT', '100', 'NUMBER', 'Rate limit per minute'],
                ['SESSION_TIMEOUT', '86400', 'NUMBER', 'Session timeout in seconds'],
                ['PASSWORD_MIN_LENGTH', '6', 'NUMBER', 'Minimum password length'],
                ['SYSTEM_VERSION', '1.0.0', 'STRING', 'System version'],
                ['ENVIRONMENT', 'development', 'STRING', 'Environment type']
            ];

            for (const [key, value, type, description] of defaultConfigs) {
                try {
                    await executeQuery(`
                        INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
                        SELECT '${key}', '${value}', '${type}', '${description}', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                        FROM DUAL
                        WHERE NOT EXISTS (SELECT 1 FROM SYSTEM_CONFIG WHERE CONFIG_KEY = '${key}')
                    `);
                } catch (error) {
                    console.log(`Config ${key} may already exist`);
                }
            }
            console.log('Default system configuration inserted');

            try {
                await executeQuery(`CREATE INDEX IDX_ADMIN_LOGS_ADMIN_ID ON ADMIN_LOGS(ADMIN_ID)`);
                await executeQuery(`CREATE INDEX IDX_ADMIN_LOGS_CREATED_AT ON ADMIN_LOGS(CREATED_AT)`);
                await executeQuery(`CREATE INDEX IDX_SYSTEM_CONFIG_KEY ON SYSTEM_CONFIG(CONFIG_KEY)`);
                console.log('Indexes created successfully');
            } catch (error) {
                console.log('Some indexes may already exist');
            }

        } catch (error) {
            console.error('Error creating admin tables:', error);
            throw error;
        }
    }

    static async createSuperAdmin() {
        try {
            console.log('Creating Super Admin...');

            const existingAdmin = await executeQuery(
                `SELECT ID FROM USERS WHERE EMAILI = 'admin@diploma.al' AND ROLI = 'admin'`
            );

            if (existingAdmin.rows.length > 0) {
                console.log('Super Admin already exists');
                return existingAdmin.rows[0].ID;
            }

            const hashedPassword = await bcrypt.hash('Admin123!', 12);

            await executeQuery(`
                INSERT INTO USERS (
                    EMRI, SURNAME, EMAILI, PASSWORDI, ROLI, IS_VERIFIED, 
                    CREATED_AT, UPDATED_AT
                )
                VALUES (
                    'Super', 'Admin', 'admin@diploma.al', '${hashedPassword}', 'admin', 1,
                    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                )
            `);

            const adminResult = await executeQuery(
                `SELECT ID FROM USERS WHERE EMAILI = 'admin@diploma.al' ORDER BY CREATED_AT DESC FETCH FIRST 1 ROWS ONLY`
            );

            const adminId = adminResult.rows[0]?.ID;

            if (adminId) {
                console.log('Super Admin created successfully');
                console.log('Email: admin@diploma.al');
                console.log('Password: Admin123!');
                console.log(`Admin ID: ${adminId}`);
                return adminId;
            }

        } catch (error) {
            console.error('Failed to create Super Admin:', error);
            return false;
        }
    }

    static async seedDefaultData() {
        try {
            console.log('Seeding default admin data...');
            // await this.createSampleTests(); // DISABLED - Don't create automatic tests
            await this.createSampleChatRooms();
            console.log('Default data seeded successfully');
        } catch (error) {
            console.error('Failed to seed default data:', error);
        }
    }

    static async createSampleTests() {
        // THIS METHOD IS DISABLED TO PREVENT AUTOMATIC TEST CREATION
        console.log('Sample test creation is disabled');
        return;
        
        
    }

    static async createSampleChatRooms() {
        try {
            const adminResult = await executeQuery(
                `SELECT ID FROM USERS WHERE ROLI = 'ADMIN' FETCH FIRST 1 ROWS ONLY`
            );

            const adminId = adminResult.rows[0]?.ID;

            if (adminId) {
                const rooms = [
                    {
                        name: 'General Discussion',
                        description: 'General chat for all users - discuss career topics and share experiences',
                        type: 'PUBLIC'
                    },
                    {
                        name: 'Study Group',
                        description: 'Academic discussions and study help for students and professionals',
                        type: 'STUDY'
                    },
                    {
                        name: 'Career Guidance',
                        description: 'Get advice from counselors and experienced professionals',
                        type: 'GUIDANCE'
                    },
                    {
                        name: 'Technical Skills',
                        description: 'Discuss programming, design, and other technical skills',
                        type: 'TECHNICAL'
                    }
                ];

                for (const room of rooms) {
                    try {
                        const existing = await executeQuery(
                            `SELECT ROOM_ID FROM CHAT_ROOMS WHERE ROOM_NAME = '${room.name}'`
                        );

                        if (existing.rows.length === 0) {
                            await executeQuery(`
                                INSERT INTO CHAT_ROOMS (ROOM_NAME, DESCRIPTION, ROOM_TYPE, CREATED_BY, IS_PRIVATE, IS_ACTIVE, CREATED_AT)
                                VALUES ('${room.name}', '${room.description}', '${room.type}', ${adminId}, 0, 1, CURRENT_TIMESTAMP)
                            `);
                            console.log(`Created chat room: ${room.name}`);
                        } else {
                            console.log(`Chat room already exists: ${room.name}`);
                        }
                    } catch (error) {
                        console.error(`Failed to create chat room ${room.name}:`, error.message);
                    }
                }
            } else {
                console.log('No admin user found for chat room creation');
            }
        } catch (error) {
            console.error('Error in createSampleChatRooms:', error.message);
        }
    }

    static async logInitialAdminAction(adminId) {
        try {
            await executeQuery(`
                INSERT INTO ADMIN_LOGS (ADMIN_ID, ACTION_TYPE, DESCRIPTION, IP_ADDRESS, CREATED_AT)
                VALUES (${adminId}, 'SYSTEM_INIT', 'Initial admin setup and system configuration', 'localhost', CURRENT_TIMESTAMP)
            `);
            console.log('Initial admin action logged');
        } catch (error) {
            console.error('Failed to log initial admin action:', error.message);
        }
    }

    static async run() {
        try {
            console.log('Starting Complete Admin Setup...');
            
            console.log('Initializing database connection...');
            await initializeDatabase();
            console.log('Database connection initialized');
            
            await this.createAdminTables();
            const adminId = await this.createSuperAdmin();
            await this.seedDefaultData();
            
            if (adminId) {
                await this.logInitialAdminAction(adminId);
            }
            
            console.log('Complete Admin Setup completed successfully!');
            console.log('');
            console.log('SETUP SUMMARY:');
            console.log('==================');
            console.log('Admin tables created');
            console.log('Super admin user created');
            console.log('System configuration initialized');
            console.log('Sample chat rooms created (tests disabled)');
            console.log('Admin logging system ready');
            console.log('');
            console.log('ADMIN LOGIN CREDENTIALS:');
            console.log('============================');
            console.log('Email: admin@diploma.al');
            console.log('Password: Admin123!');
            console.log('Role: ADMIN');
            console.log('');
            console.log('IMPORTANT: Change the admin password after first login!');
            
        } catch (error) {
            console.error('Complete Admin Setup failed:', error);
        } finally {
            try {
                console.log('Closing database connection...');
                await closeDatabase();
                console.log('Database connection closed');
            } catch (closeError) {
                console.error('Error closing database:', closeError);
            }
            
            process.exit(0);
        }
    }
}

if (require.main === module) {
    AdminSeeder.run();
}

module.exports = AdminSeeder;